# Generated by Django 3.2.7 on 2021-10-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('video_url', models.TextField()),
            ],
        ),
    ]
